"""
PyAegis GitHub Actions integration generator.

Generates a GitHub Actions workflow YAML that:
  - Runs PyAegis on every push / pull-request
  - Uploads SARIF results to GitHub Code Scanning (Security tab)
"""
from __future__ import annotations


def generate_github_actions_workflow(
    python_version: str = "3.11",
    rules_path: str = "pyaegis/rules/default.yml",
    sarif_output: str = "pyaegis-results.sarif",
    fail_on_findings: bool = True,
) -> str:
    """
    Return a GitHub Actions workflow YAML string.

    Parameters
    ----------
    python_version:
        Python version used in the scan job.
    rules_path:
        Path to the PyAegis rules YAML file inside the repository.
    sarif_output:
        Filename for the SARIF output artifact.
    fail_on_findings:
        If True the workflow step exits with code 1 on findings.
        Set to False to upload results without failing the build.
    """
    exit_zero = "" if fail_on_findings else " || true"
    return f"""# .github/workflows/pyaegis.yml
# Auto-generated by: pyaegis init --ci github
# PyAegis SAST scan + GitHub Code Scanning SARIF upload

name: PyAegis Security Scan

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]
  schedule:
    # Run weekly on Monday 02:00 UTC
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  pyaegis-scan:
    name: Static Security Analysis
    runs-on: ubuntu-latest
    permissions:
      # Required for uploading SARIF to GitHub Code Scanning
      security-events: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python {python_version}
        uses: actions/setup-python@v5
        with:
          python-version: "{python_version}"
          cache: pip

      - name: Install PyAegis
        run: pip install pyaegis

      - name: Run PyAegis scan (SARIF output)
        run: |
          pyaegis . \\
            --rules {rules_path} \\
            --format sarif \\
            --output {sarif_output}{exit_zero}

      - name: Upload SARIF to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: {sarif_output}
          category: pyaegis

      - name: Archive SARIF artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pyaegis-sarif
          path: {sarif_output}
          retention-days: 30
"""


if __name__ == "__main__":  # pragma: no cover
    print(generate_github_actions_workflow())
