"""
PyAegis GitLab CI integration generator.

Generates a GitLab CI YAML snippet that:
  - Runs PyAegis in the test stage
  - Emits a SAST SARIF artifact consumed by GitLab Security Dashboard
"""
from __future__ import annotations


def generate_gitlab_ci_snippet(
    python_version: str = "3.11",
    rules_path: str = "pyaegis/rules/default.yml",
    sarif_output: str = "pyaegis-results.sarif",
    stage: str = "test",
    fail_on_findings: bool = True,
) -> str:
    """
    Return a GitLab CI YAML snippet string.

    Parameters
    ----------
    python_version:
        Docker image Python version tag.
    rules_path:
        Path to rules YAML inside the repo.
    sarif_output:
        SARIF output filename (stored as a GitLab artifact).
    stage:
        GitLab CI stage name.
    fail_on_findings:
        Controls whether the job fails when findings are detected.
    """
    allow_failure = "true" if not fail_on_findings else "false"
    return f"""# GitLab CI snippet — auto-generated by: pyaegis init --ci gitlab
# Paste into your .gitlab-ci.yml (merge with existing stages/variables as needed)

stages:
  - {stage}

variables:
  PYAEGIS_RULES: "{rules_path}"
  PYAEGIS_SARIF: "{sarif_output}"

pyaegis-sast:
  stage: {stage}
  image: python:{python_version}-slim
  allow_failure: {allow_failure}
  before_script:
    - pip install --quiet pyaegis
  script:
    - |
      pyaegis . \\
        --rules "$PYAEGIS_RULES" \\
        --format sarif \\
        --output "$PYAEGIS_SARIF"
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - $PYAEGIS_SARIF
    reports:
      # GitLab 15.0+: import SARIF as SAST report
      sast: $PYAEGIS_SARIF
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH =~ /^develop/'
"""


if __name__ == "__main__":  # pragma: no cover
    print(generate_gitlab_ci_snippet())
