"""
PyAegis pre-commit hook configuration generator.

Generates a .pre-commit-config.yaml snippet that runs PyAegis
as a local hook on every git commit.
"""
from __future__ import annotations


def generate_pre_commit_config(
    pyaegis_rev: str = "v0.2.0",
    rules_path: str = "pyaegis/rules/default.yml",
    extra_args: list[str] | None = None,
    use_local: bool = False,
) -> str:
    """
    Return a .pre-commit-config.yaml snippet string.

    Parameters
    ----------
    pyaegis_rev:
        Git tag / revision to pin for the remote repo hook.
    rules_path:
        Path to rules YAML passed as an extra arg.
    extra_args:
        Additional CLI arguments forwarded to pyaegis.
    use_local:
        If True, emit a ``local`` repo hook (uses the venv-installed
        pyaegis) instead of the remote repo hook.
    """
    args = extra_args or []
    args_lines = ""
    if args:
        args_lines = "\n".join(f"          - {a}" for a in args)
        args_lines = "\n" + args_lines

    if use_local:
        return f"""# .pre-commit-config.yaml snippet
# Auto-generated by: pyaegis init --ci precommit
# Uses the locally-installed pyaegis (pip install pyaegis)

repos:
  - repo: local
    hooks:
      - id: pyaegis
        name: PyAegis Security Scanner
        language: system
        entry: pyaegis
        args:
          - "."
          - --rules
          - "{rules_path}"
          - --format
          - text{args_lines}
        types: [python]
        pass_filenames: false
        verbose: true
"""
    else:
        return f"""# .pre-commit-config.yaml snippet
# Auto-generated by: pyaegis init --ci precommit
# Run: pre-commit install   (first time)
#      pre-commit run --all-files  (manual scan)

repos:
  - repo: https://github.com/mnbplus/PyAegis
    rev: {pyaegis_rev}
    hooks:
      - id: pyaegis
        name: PyAegis Security Scanner
        language: python
        entry: pyaegis
        args:
          - "."
          - --rules
          - "{rules_path}"
          - --format
          - text{args_lines}
        types: [python]
        pass_filenames: false
        verbose: true
        stages: [pre-commit, manual]
"""


if __name__ == "__main__":  # pragma: no cover
    print(generate_pre_commit_config())
