[tox]
envlist = py38, py39, py310, py311, py312, lint, type
isolated_build = True

[testenv]
deps =
    pytest>=7.4.0
    pytest-cov>=4.1.0
commands =
    pytest tests/ --cov=pyaegis --cov-report=term-missing

[testenv:lint]
deps =
    black>=23.9.1
    flake8>=6.1.0
commands =
    black --check pyaegis tests
    flake8 pyaegis tests

[testenv:type]
deps =
    mypy>=1.5.1
    types-PyYAML
commands =
    mypy pyaegis
